version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: yarn --unsafe-perm
  - &update-npm
    run:
      name: Update NPM version
      command: "sudo npm install -g npm@latest"
  - &run-lint
    run:
      name: Linting
      command: yarn lint
  - &run-integration
    run:
      name: Integration tests
      command: yarn test:integration
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &install-yarn
    run:
      name: Install yarn
      command: npm i -g yarn

jobs:
  integration_tests_node_12:
    working_directory: ~/nest
    docker:
      - image: cimg/node:12.22.0
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  integration_tests_node_14:
    working_directory: ~/nest
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  integration_tests_node_16:
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  integration_tests_node_18:
    working_directory: ~/nest
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  "integration_tests_node_18_nest_7.x":
    working_directory: ~/nest
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - *run-integration
      - run:
          name: Remove latest nestjs
          command: npm uninstall @nestjs/{common,core,platform-express,testing}
      - run:
          name: Install nestjs 7.x
          command: yarn add -D @nestjs/{common,core,platform-express,testing}@^7.0.0

  coverage:
    working_directory: ~/nest
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-yarn
      - *install-deps
      - *save-cache
      - run:
          name: Test coverage
          command: npm run test:cov
      - coveralls/upload:
          path_to_lcov: ./coverage/e2e/lcov.info

workflows:
  version: 2
  test:
    jobs:
      - integration_tests_node_12
      - integration_tests_node_14
      - integration_tests_node_16
  coverage:
    jobs:
      - coverage
